[project]
name = "uni-ai-studio"
version = "0.1.0"
description = "Reinforcement Learning (RL) for a Game"
readme = "README.md"
requires-python = "==3.12.7"
dependencies = [
    "numpy>=2.3.0",
    "pygame>=2.6.1",
]
